# .gitlab-ci.yml

# Define stages for the CI/CD pipeline
stages:
  - build
  - test
  - deploy

# Define job for building the project
build:
  stage: build
  script:
    - npm install  # Install dependencies
    - npm run build  # Build the project
  artifacts:
    paths:
      - public/  # Specify artifacts to be passed to the next stages

# Define job for running tests
test:
  stage: test
  script:
    - npm run test  # Run tests
  artifacts:
    paths:
      - coverage/  # Specify test coverage reports to be passed to the next stages

# Define job for deploying the project
deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."  # Placeholder for deployment script
  environment:
    name: production
  only:
    - main  # Deploy only from the main branch
